# Generated by Django 5.2 on 2025-04-29 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0017_venueratingmodel_rated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Ongoing', 'Ongoing')], default='Ongoing', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='venueratingmodel',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='venue.venuemodel'),
        ),
    ]
