# Generated by Django 5.2 on 2025-04-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0019_khaltitransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khaltitransaction',
            old_name='txnId',
            new_name='txn_id',
        ),
        migrations.RemoveField(
            model_name='khaltitransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='khaltitransaction',
            name='mobile',
        ),
    ]
