# Generated by Django 5.2 on 2025-12-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0020_rename_txnid_khaltitransaction_txn_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venuemodel',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
